### ISSUE TITLE
Issue using from OSX

### ISSUE THREAD

**Issue by jogster** [xuwang/coreos-docker-registry#2]
Hi,
I managed to run run the registry as is, and was able to test that it worked when I was ssh'd into core-01.

Unfortunately I have been unable to log onto the registry from my local Mac OSX machine. I keep getting the following errors below.

I am hesitant to make too many changes as I am unfamiliar with using configd, skydns and nginx. I have instead used consul-template, consul dns and haproxy.

Normally I would build individual service files and merge them to form the user-data and let systemd run things instead of fleetctl... 

Any help with shedding light on the problem below would be appreciated.
###### ### ERROR

docker login -u test -p test https://172.17.0.101
Email: a@b.com
Error response from daemon: invalid registry endpoint https://172.17.0.101/v0/: unable to ping registry endpoint https://172.17.0.101/v0/
v2 ping attempt failed with error: Get https://172.17.0.101/v2/: dial tcp 172.17.0.101:443: getsockopt: no route to host
 v1 ping attempt failed with error: Get https://172.17.0.101/v1/_ping: dial tcp 172.17.0.101:443: getsockopt: no route to host. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.17.0.101` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.17.0.101/ca.crt

**Comment by jogster** [comment]
I think I have realised my problem... I have to actually install my own server certificates into the correct places so that they installed on the server correctly. Is this the issue?

**Comment by xueshanf** [comment]
The docker address should be 172.17.8.101 if you haven't changed the Vagrant file. Could you try that and see if it works?

**Comment by jogster** [comment]
Thanks for getting back.

I changed the Vagrantfile back to the original value e.g. base_ip=172.17.8

Note that everything works fine if I vagrant ssh onto core-01

But I still get the same errors, when running from my local mac.

If I use curl with -k then I can hit the registry, but obviously this does not work for me as I want to setup a secure login.

I suspect it is certificates (or security related) but I can't say that for sure... Again any pointers to what I could do to resolve this would be a great help....

####
docker login -u test -p test -e test@example.com https://172.17.8.101
Error response from daemon: invalid registry endpoint https://172.17.8.101/v0/: unable to ping registry endpoint https://172.17.8.101/v0/
v2 ping attempt failed with error: Get https://172.17.8.101/v2/: dial tcp 172.17.8.101:443: getsockopt: no route to host
 v1 ping attempt failed with error: Get https://172.17.8.101/v1/_ping: dial tcp 172.17.8.101:443: getsockopt: no route to host. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 172.17.8.101` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/172.17.8.101/ca.crt

Nothing shows in the registry logs -- which means that it is stopped by nginx

####

I then tried using the curl example:
######
curl -D -  --user test:test https://172.17.8.101/v2/
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
#####

So I added the -k option, it looks like it is routing through nginx and looked in the registry log:

######
curl -k -D -  --user test:test https://172.17.8.101/v2/
HTTP/1.1 200 OK
Server: nginx/1.9.14
Date: Mon, 25 Apr 2016 09:09:55 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Docker-Distribution-Api-Version: registry/2.0

{}

time="2016-04-25T09:09:55.110721329Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=172.17.8.101 http.request.id=0180040a-b727-4a64-8824-cf00d82bbe33 http.request.method=GET http.request.remoteaddr=172.17.8.1 http.request.uri="/v2/" http.request.useragent="curl/7.43.0" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.179131ms http.response.status=200 http.response.written=2 instance.id=2095dafa-a660-4bb8-8559-d0bba255be04 service=registry version=v2.2.1 
172.18.0.1 - - [25/Apr/2016:09:09:55 +0000] "GET /v2/ HTTP/1.0" 200 2 "" "curl/7.43.0"

######

**Comment by xuwang** [comment]
Because the regsitry is using a self-signed certificate, curl the registry from the host machine, you will need to use "-k" option. 

For "docker pull" from out site of core-01, you can either install a valid cert on registry nginx or add "--insecure-registry 172.17.8.101" to your client docker daemon (see https://docs.docker.com/registry/insecure for details) .  

I add a node to the README.md to make it clear.

Thanks

**Comment by xuwang** [comment]
@jogster, without knowing your local host docker engine setup, it is hard to say what cause the routing problem.
You could try to add port forwarding the registry ports to your localhost by add following to the Vagrantfile:

```
Vagrant.configure("2") do |config|
 ...
 config.vm.network "forwarded_port", guest: 80, host: 80, protocol: "tcp"
 config.vm.network "forwarded_port", guest: 443, host: 443, protocol: “tcp"
 ...
end
```

if the port 80/443 is free on your host. You client docker box may be able to access the registry through the host.

**Comment by jogster** [comment]
Ok -- I will try that, but I think the routing is working (see below)

I think it may just be a certificate problem...

I am running  vagrant on mac-osx with a virtualbox. The registry is running on the virtualbox and I connect to it via my local docker command which is routing through a boot2docker (I think)

##########
curl -k -D - --user test:test https://172.17.8.101/v2/
HTTP/1.1 200 OK
Server: nginx/1.9.14
Date: Mon, 25 Apr 2016 09:09:55 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 2
Connection: keep-alive
Docker-Distribution-Api-Version: registry/2.0
X-Content-Type-Options: nosniff
Docker-Distribution-Api-Version: registry/2.0

{}

time="2016-04-25T09:09:55.110721329Z" level=info msg="response completed" go.version=go1.5.2 http.request.host=172.17.8.101 http.request.id=0180040a-b727-4a64-8824-cf00d82bbe33 http.request.method=GET http.request.remoteaddr=172.17.8.1 http.request.uri="/v2/" http.request.useragent="curl/7.43.0" http.response.contenttype="application/json; charset=utf-8" http.response.duration=3.179131ms http.response.status=200 http.response.written=2 instance.id=2095dafa-a660-4bb8-8559-d0bba255be04 service=registry version=v2.2.1 
172.18.0.1 - - [25/Apr/2016:09:09:55 +0000] "GET /v2/ HTTP/1.0" 200 2 "" "curl/7.43.0"
